import * as THREE from 'three';
import { getTerrainHeight } from './terrainHeight.js';

// ================== COLLECTIBLES (herb gathering) ==================
// Gathering points tied to a quest. They appear in the world only when the
// quest is ACTIVE; getting close shows a "Press F to gather" banner and a
// micro-card with the item's name + description. Pressing F gathers the item,
// it disappears and once the total is reached a flag is set


const PICK_RADIUS = 4;     // distance within which gathering is possible

export function createCollectibles(scene, quests, cfg) {
  const { questId, flag, total, item, spots } = cfg;

  // herb 3D: a bright blue-green streak generated by code 
  function makeHerb() {
    const g = new THREE.Group();
    const bladeMat = new THREE.MeshStandardMaterial({
      color: 0x9be8c0, emissive: 0x3fae7a, emissiveIntensity: 0.6, roughness: 0.5,
    });
    // a few thin leaves arranged in a tuft
    for (let i = 0; i < 6; i++) {
      const h = 0.8 + Math.random() * 0.5;
      const blade = new THREE.Mesh(new THREE.ConeGeometry(0.07, h, 5), bladeMat);
      const a = (i / 6) * Math.PI * 2;
      blade.position.set(Math.cos(a) * 0.12, h / 2, Math.sin(a) * 0.12);
      blade.rotation.z = Math.cos(a) * 0.25;
      blade.rotation.x = -Math.sin(a) * 0.25;
      g.add(blade);
    }
    // a small glow at the center
    const glow = new THREE.Mesh(
      new THREE.SphereGeometry(0.18, 8, 8),
      new THREE.MeshBasicMaterial({ color: 0xcffce4, transparent: true, opacity: 0.7 })
    );
    glow.position.y = 0.5;
    g.add(glow);
    g.scale.setScalar(1.6);
    return g;
  }

  // create the herbs at the given points (hidden until the quest is active)
  const herbs = spots.map(s => {
    const mesh = makeHerb();
    mesh.position.set(s.x, getTerrainHeight(s.x, s.z), s.z);
    mesh.visible = false;
    scene.add(mesh);
    return { mesh, x: s.x, z: s.z, collected: false };
  });

  let spawned = false;   // herbs shown in the world
  let gathered = 0;

  // UI: banner "Press F" + object micro-card 
  const banner = document.createElement('div');
  banner.style.cssText = `
    position:fixed; left:50%; bottom:20%; transform:translateX(-50%); z-index:60;
    font-family: Georgia, serif; color:#eafff2; display:none;
    background:rgba(20,40,30,.88); border:1px solid #6fcf9a; border-radius:20px;
    padding:8px 18px; font-size:15px; box-shadow:0 4px 14px rgba(0,0,0,.5);`;
  banner.textContent = 'Press  F  to gather';
  document.body.appendChild(banner);

  // object micro-card : icon + name + description
  const card = document.createElement('div');
  card.style.cssText = `
    position:fixed; left:50%; bottom:26%; transform:translateX(-50%); z-index:60;
    font-family: Georgia, serif; color:#eafff2; display:none; width:260px;
    background:linear-gradient(180deg, rgba(22,44,33,.95), rgba(14,30,22,.95));
    border:1px solid #6fcf9a; border-radius:10px; padding:12px 14px;
    box-shadow:0 8px 24px rgba(0,0,0,.55);`;
  card.innerHTML = `
    <div style="display:flex; align-items:center; gap:12px;">
      <div style="flex:0 0 auto; width:44px; height:44px; border-radius:8px;
                  background:radial-gradient(circle at 50% 35%, #cffce4, #3fae7a);
                  box-shadow:0 0 12px #6fcf9a; position:relative;">
        <div style="position:absolute; left:50%; top:8px; width:4px; height:28px;
                    background:#1d6b48; border-radius:2px; transform:translateX(-50%);"></div>
      </div>
      <div>
        <div style="font-size:16px; font-weight:bold; color:#bfffd9;">${item.name}</div>
        <div style="font-size:12px; line-height:1.35; color:#a9d8bf;">${item.desc}</div>
      </div>
    </div>`;
  document.body.appendChild(card);

  // F key: gathers the nearby herb (if any)
  let nearHerb = null;
  window.addEventListener('keydown', (e) => {
    if (e.code === 'KeyF' && nearHerb && !nearHerb.collected) {
      nearHerb.collected = true;
      nearHerb.mesh.visible = false;
      gathered++;
      // update the objective shown in the quest panel
      if (quests.setObjective) {
        const done = gathered >= total;
        quests.setObjective(
          questId,
          `Gathered ${gathered}/${total} moon herbs. Bring them back to Alaric.`,
          done   // ready=true on completion -> the quest panel lights up
        );
      }
      // at the total: set the flag (unlocks the turn-in in the dialogue)
      if (gathered >= total) quests.setFlag(flag, true);
      // hide banner+card immediately
      banner.style.display = 'none';
      card.style.display = 'none';
      nearHerb = null;
    }
  });

  function update(t, playerPos) {
    const active = quests.status(questId) === 'active' && !quests.flag(flag);

    // spawn/despawn herbs based on the quest state
    if (active && !spawned) {
      for (const h of herbs) if (!h.collected) h.mesh.visible = true;
      spawned = true;
    } else if (!active && spawned) {
      for (const h of herbs) h.mesh.visible = false;
      banner.style.display = 'none'; card.style.display = 'none';
      spawned = false;
    }

    if (!active) { nearHerb = null; return; }

    // animation: slight swaying + rotation of the glow
    for (const h of herbs) {
      if (h.mesh.visible) {
        h.mesh.rotation.y = t * 0.6;
        h.mesh.position.y = getTerrainHeight(h.x, h.z) + Math.sin(t * 2 + h.x) * 0.08;
      }
    }

    // proximity: nearest herb within the radius
    let best = null, bestD2 = PICK_RADIUS * PICK_RADIUS;
    for (const h of herbs) {
      if (h.collected) continue;
      const dx = h.x - playerPos.x, dz = h.z - playerPos.z;
      const d2 = dx*dx + dz*dz;
      if (d2 < bestD2) { bestD2 = d2; best = h; }
    }
    nearHerb = best;
    if (best) { banner.style.display = 'block'; card.style.display = 'block'; }
    else      { banner.style.display = 'none';  card.style.display = 'none'; }
  }

  return { update, get gathered() { return gathered; } };
}